let cloth = [
  {
    id: 1,
    img: "image/baseball.jpg",
    desc: "Baseball Bat",
    price: 450,
  },
  {
    id: 2,
    img: "image/bag.jpg",
    desc: "Travel Bag",
    price: 750,
  },
  {
    id: 3,
    img: "image/cap.jpg",
    desc: "Sports Cap",
    price: 220,
  },
  {
    id: 4,
    img: "image/book.jpg",
    desc: "Programming Book",
    price: 399,
  },
  {
    id: 5,
    img: "image/winter1.jpg",
    desc: "Winter Jacket",
    price: 1200,
  },
  {
    id: 6,
    img: "image/winter.jpg",
    desc: "Wool Sweater",
    price: 950,
  },
  {
    id: 7,
    img: "image/winter1.jpg",
    desc: "Casual Hoodie",
    price: 850,
  },
  {
    id: 8,
    img: "image/virat.jpg",
    desc: "Casual Shirt",
    price: 550,
  },
  {
    id: 9,
    img: "image/shoes.jpg",
    desc: "Running Shoes",
    price: 1800,
  },
  {
    id: 10,
    img: "image/sliper.jpg",
    desc: "Casual Slippers",
    price: 300,
  },
  {
    id: 11,
    img: "image/speaker.jpg",
    desc: "Bluetooth Speaker",
    price: 2200,
  },
  {
    id: 12,
    img: "image/sunglass.jpg",
    desc: "Stylish Sunglasses",
    price: 450,
  },
  {
    id: 13,
    img: "image/watch.jpg",
    desc: "Wrist Watch",
    price: 1500,
  },
  {
    id: 14,
    img: "image/ring.jpg",
    desc: "Diamond Ring",
    price: 5200,
  },
  {
    id: 15,
    img: "image/shoes.jpg",
    desc: "Ethnic Saree",
    price: 2500,
  },
  {
    id: 16,
    img: "image/payment1.jpg",
    desc: "Graphic T-shirt",
    price: 499,
  },
  {
    id: 17,
    img: "image/pufium.jpg",
    desc: "Luxury Perfume",
    price: 999,
  },
  {
    id: 18,
    img: "image/tablet.jpg",
    desc: "Android Tablet",
    price: 12000,
  },
  {
    id: 19,
    img: "image/shoes.jpg",
    desc: "Formal Shoes",
    price: 2200,
  },
  {
    id: 20,
    img: "image/tanisk.png",
    desc: "Gold Necklace",
    price: 25000,
  },
  {
    id: 21,
    img: "image/led.jpg",
    desc: "LED Light",
    price: 650,
  },
   {
    id: 22,
    img: "image/payment1.jpg",
    desc: "Graphic T-shirt",
    price: 499,
  }, {
    id: 23,
    img: "image/tablet.jpg",
    desc: "Android Tablet",
    price: 12000,
  }, {
    id: 24,
    img: "image/pufium.jpg",
    desc: "Luxury Perfume",
    price: 999,
  },
];
export default cloth;
